import Head from "next/head";
import PropTypes from "prop-types";
import { connect } from "react-redux";
import { compose } from "redux";
import { useEffect } from "react";
import { getCourse } from "../redux/actions/Home";
const Home = ({ courses, error, isLoading, actionGetCourses }) => {
  useEffect(() => {
    actionGetCourses();
  }, []);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <button className="btn  btn-primary"> test</button>
      </main>
    </div>
  );
};

Home.defaultProps = {
  courses: null,
  isLoading: true,
  error: null,
};

Home.propTypes = {
  courses: PropTypes.array,
  error: PropTypes.object,
  isLoading: PropTypes.bool,
  actionGetCourses: PropTypes.func,
};

const mapStateToProps = (state) => ({
  courses: state.homeReducer.courses,
  error: state.homeReducer.error,
  isLoading: state.homeReducer.isLoading,
});

export function mapDispatchToProps(dispatch) {
  return {
    actionGetCourses: (payload) => dispatch(getCourse(payload)),
  };
}

const withConnect = connect(mapStateToProps, mapDispatchToProps);

export default compose(withConnect)(Home);
